### PR TITLE
Swedish localisation 

### PR DESCRIPTION
**Pull request by Mhdtarek**
Added Swedish localisation.
I hope it works, since this was all made on my phone

### CODE REVIEW

**Comment by Mhdtarek** [comment]
Ya rab! Why is this not working!

**Comment by Mhdtarek** [comment]
Its not working on my pc as well i will check back tommorow

**Comment by mr-islam** [comment]
May Allah make it easy and reward you :)

**Comment by Mhdtarek** [comment]
Can not find what the issue is @mr-islam can you help?

**Comment by Mhdtarek** [comment]
Can't find what the bug is?

Also, netlify says that netlify is saying that you are using an unsupported image.

 @mr-islam

**Comment by mr-islam** [comment]
InshaAllah I'll take a closer look today or tomorrow :)

I need to sort out Netlify, I haven't touched it in a while 😅

**Comment by mr-islam** [comment]
So, your localization code looks perfect, and I'm only getting some errors from other dependencies. I haven't been able to work on Layl in some time, so it needs some maintenance first.

InshaAllah I'll fix them soon, and after that I'll merge this PR 🌹

Thank you again!

**Comment by mr-islam** [comment]
I'm very sorry for the delay brother @Mhdtarek, I still haven't had a chance to debug the issue in the main repo (studies have been heavy)

But I've gone through your PR in detail, everything looks fine so I'll merge it now and fix the other problem later 👍

**Pull request merged**
