### PR TITLE
Transition to Vite

### PR DESCRIPTION
**Pull request by Mhdtarek**
I have transitioned the App from Sirv to Vite. The process was straightforward Alhamdulilah.
Some things to keep in mind: 
- [x] App working.
- [x] same RUN commands as the previous version.
- [x] favicons and logos.
- [x] PWA.

You may have to change some settings in Netlify but Inshallah this works.

### CODE REVIEW

**Comment by Mhdtarek** [comment]
@mr-islam 
bild

**Comment by Mhdtarek** [comment]
Also this closes #68

**Comment by Mhdtarek** [comment]
If i am not wrong everything should be done.

**Comment by mr-islam** [comment]
Allah reward you abundantly my brother! 

MashaAllah, going through a repo like this and porting it to a new base is really impressive. It is a pleasure to work with you and I look forward to collaborating more in the future inshaAllah 💚.

Everything looks good and I tested to 2x check. I'm adding the license and making some small adjustments to the readme, and footer before merging.

**Comment by mr-islam** [comment]
Closes #68 

I'll go make the changes to Netlify for the deployment. I've actually started using Cloudflare Pages since after Layl, so I think I'll move it there.

After that, I'll make the update for Google Play inshaAllah.

**Pull request merged**
